services:
  proyekabl:
    build: ./php
    image: proyekabl_php:latest
    container_name: proyekabl
    hostname: "proyekabl"
    volumes:
      - ./src:/var/www/html
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
    depends_on:
      - proyekabl_db

  proyekabl_db:
    image: mariadb:10.11
    container_name: proyekabl-db
    restart: unless-stopped
    tty: true
    ports:
      - "13306:3306"
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/conf.d:/etc/mysql/conf.d:ro
    environment:
      MYSQL_USER: rassyz
      MYSQL_PASSWORD: p455w0rd1!.
      MYSQL_ROOT_PASSWORD: p455w0rd
      TZ: Asia/Jakarta
      SERVICE_TAGS: dev
      SERVICE_NAME: proyekabl_db

  proyekabl_nginx:
    build: ./nginx
    image: proyekabl_nginx:latest
    container_name: proyekabl-nginx
    hostname: "proyekabl-nginx"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - proyekabl
